/**
 * Articles page
 */
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import ArticleList from '../components/content/ArticleList';
import ArticleEditor from '../components/content/ArticleEditor';
import * as contentAPI from '../api/content';
import { useWorkspaceStore } from '../store/workspaceStore';

export default function Articles() {
  const { currentWorkspaceId } = useWorkspaceStore();
  const [showEditor, setShowEditor] = useState(false);
  const [editingArticleId, setEditingArticleId] = useState<string | null>(null);
  const [viewingArticleId, setViewingArticleId] = useState<string | null>(null);

  // For viewing article
  const articleQuery = useQuery({
    queryKey: ['article', viewingArticleId],
    queryFn: () => contentAPI.getArticle(viewingArticleId!),
    enabled: !!viewingArticleId,
  });

  if (!currentWorkspaceId) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Articles</h1>
          <p className="text-gray-500">
            Manage your SEO articles and content.
          </p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-12 text-center">
          <p className="text-gray-500">
            Please select a workspace to manage articles.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Articles</h1>
        <p className="text-gray-500">
          Manage your SEO articles and content.
        </p>
      </div>

      {showEditor && (
        <ArticleEditor
          workspaceId={currentWorkspaceId}
          onClose={() => setShowEditor(false)}
          onSuccess={() => setShowEditor(false)}
        />
      )}

      {editingArticleId && (
        <ArticleEditor
          workspaceId={currentWorkspaceId}
          articleId={editingArticleId}
          onClose={() => setEditingArticleId(null)}
          onSuccess={() => setEditingArticleId(null)}
        />
      )}

      {viewingArticleId && articleQuery.data && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="flex h-[90vh] w-full max-w-4xl flex-col rounded-lg bg-white shadow-xl">
            <div className="flex items-center justify-between border-b border-gray-200 px-6 py-4">
              <h3 className="text-lg font-medium text-gray-900">
                {articleQuery.data.title}
              </h3>
              <button
                onClick={() => setViewingArticleId(null)}
                className="rounded-md border border-gray-300 px-3 py-1 text-sm text-gray-600 hover:bg-gray-50"
              >
                Close
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              <div className="mb-4 flex items-center gap-4">
                <span
                  className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                    articleQuery.data.status === 'published'
                      ? 'bg-green-100 text-green-800'
                      : 'bg-yellow-100 text-yellow-800'
                  }`}
                >
                  {articleQuery.data.status}
                </span>
                <span className="text-sm text-gray-500">
                  {articleQuery.data.word_count} words
                </span>
                {articleQuery.data.ai_model_used && (
                  <span className="text-sm text-purple-600">
                    Generated by {articleQuery.data.ai_model_used}
                  </span>
                )}
              </div>
              <div className="prose max-w-none">
                <div
                  dangerouslySetInnerHTML={{
                    __html: articleQuery.data.content
                      .split('\n')
                      .map((line) => `<p>${line}</p>`)
                      .join(''),
                  }}
                />
              </div>
            </div>
            <div className="flex justify-end gap-3 border-t border-gray-200 px-6 py-4">
              <button
                onClick={() => {
                  setViewingArticleId(null);
                  setEditingArticleId(articleQuery.data.id);
                }}
                className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700"
              >
                Edit
              </button>
            </div>
          </div>
        </div>
      )}

      <ArticleList
        onCreateNew={() => setShowEditor(true)}
        onEdit={(id) => setEditingArticleId(id)}
        onView={(id) => setViewingArticleId(id)}
      />
    </div>
  );
}
